### ISSUE TITLE
Optimize Code

### ISSUE THREAD

**Issue by MoritzMennenga** [ISAAKiel/recexcavAAR#3]

**Comment by MoritzMennenga** [comment]
I will start with marking the critical code sections and translating the comments in the code

**Comment by nevrome** [comment]
I did something in 9d54a55cd3d12731b420a025e288bf3d87a6c5e4. The changes don't go really deep, so I'm confident that I didn't break anything. 

A next step could be to get rid of the loops and outsource some of the heavy mathing in helper functions. But: I don't think this is really necessary. See #8 for more important things to consider now.

**Comment by MoritzMennenga** [comment]
I hope so, you precisly changed the critical code part.
And please don't use Umlaute, I have to delete them, before testing it in Qgis. (Not longer relevant after the translation to english)

**Comment by nevrome** [comment]
I honestly expected the mathing chunks to be the critical ones. Didn't touch those. Sorry! The changes are really mostly cosmetic, but there's always the danger of copy&paste errors... You could use the old implementation to write the tests. 

I wondered why you avoided Umlaute, because it doesn't cause any problems in R. Didn't think about QGIS. Again sorry.
